#!/bin/bash

source scripts/top-syn-apps
apps="$top2"
source scripts/syn-app-sizes

#-E static \
./lsm-sim \
  -a 1 \
  -x 771731200 \
  -p multi \
  -E normal \
  -c 8 \
  -N 50 \
  -s 771731200 \
  -S $((1024 * 1024)) \
  -Y \
  -v \
  -w 1 \
  -R \
  -f /tmp/200.sim \
      2> multi.200.etc.normal.err \
      > multi.200.etc.normal.out

#Rscript process_output.R

#echo "./lsm-sim \
#  -a $app_lst \
#  -p multi \
#  -E normal \
#  -c 7 \
#  -N 10 \
#  -s $total_size \
#  -S $((1024 * 1024)) \
#  -Y \
#  -v \
#  -w 1 \
#  -f ./data/tiny.sim "
